# Intro to TensorFlow! This notebook is all about fundamentals!!

In [ ]:
import tensorflow as tf
print (tf.__version__)

2.6.0


In [ ]:
#Creating tensors with tf.constant()

scalar = tf.constant(7)
print (scalar.shape)
scalar

()


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Checking for dimensions
scalar.ndim

0

In [ ]:
#Creating a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Checking for dimensions
vector.ndim

1

In [ ]:
#Creating a matrix
matrix = tf.constant([[10, 7],[10, 7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [ ]:
#Checking for dimensions
matrix.ndim

2

In [ ]:
#specify data type while creating tensors

matrix2 = tf.constant([[10., 7],
                       [25., 5.],
                       [3., 4.]], dtype = tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [25.,  5.],
       [ 3.,  4.]], dtype=float16)>

In [ ]:
#Checking for dimensions
matrix2.ndim

2

In [ ]:
#Create a tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
#Checking for dimensions
tensor.ndim

3

Creating Tensors with tf.Variable

In [ ]:
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Change one of the elements in changable tensor

changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Creating Random Tensors

In [ ]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape= (3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape = (3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
#See if they are equal
random1 == random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

Shiffle the order of elements in the tensor

In [ ]:
not_shuffled = tf.constant([[5, 10],
                            [2, 3],
                            [6, 8]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5, 10],
       [ 2,  3],
       [ 6,  8]], dtype=int32)>

In [ ]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  3],
       [ 6,  8],
       [ 5, 10]], dtype=int32)>

Other ways to create tensors 

In [ ]:
ones = tf.ones([5,3], dtype = tf.int32)
ones

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [ ]:
zeros = tf.zeros(shape = (3,4), dtype = tf.int32)
zeros

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

Convert numpy arrays to tensors

In [ ]:
import numpy as np

numpy_A = np.arange(1, 25, dtype = np.int32)

tf_A = tf.constant(numpy_A)

tf_A_reshape = tf.constant(numpy_A, shape = (2,3,4))

numpy_A, tf_A, tf_A_reshape

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

Getting more information from tensors

In [ ]:
#rank
rank_4_tensor = tf.zeros(shape = (2,3,3,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 3, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 3, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=90>)

Indexing Tensors

In [ ]:
lists = [1,2,3,4]
lists[:2]

[1, 2]

In [ ]:
#output the first two elements of every dimension from a tensor
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

Add in extra dimension to our rank 2 tensor

In [ ]:
rank_2_tensor = tf.constant([[3,6],
                             [1,5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 6],
       [1, 5]], dtype=int32)>

In [ ]:
rank_3_tensor1 = rank_2_tensor[...,tf.newaxis] # add axis to the last dimenison
rank_3_tensor2 = rank_2_tensor[tf.newaxis,...] # add axis to the first dimenison
rank_3_tensor1,rank_3_tensor2 

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[3],
         [6]],
 
        [[1],
         [5]]], dtype=int32)>, <tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
 array([[[3, 6],
         [1, 5]]], dtype=int32)>)

Manuplating Tensors (Basic Tensor operations)

In [ ]:
#add values to a tensor
tensor = tf.constant([[10, 7],
                      [3, 10]])
tensor_new1 = tensor + 10

#using tf inbuilt functions
tensor_new2 = tf.add(tensor, 5)

tensor_new1, tensor_new2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 20]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[15, 12],
        [ 8, 15]], dtype=int32)>)

Matrix multiplication with tensors

In [ ]:
#Matrix multiplication
result = tf.matmul(tensor, tensor)
print (result)

#Element by element
tensor * tensor

tf.Tensor(
[[121 140]
 [ 60 121]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9, 100]], dtype=int32)>

Demonstrating the implementation of X.T @ Y, i.e. dot product between X.T and Y

In [ ]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

result1 = tf.matmul(tf.transpose(x), y)
result2 = tf.tensordot(tf.transpose(x), y, axes = 1)
#axes = 1 for matrix multiplication

result1, result2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>)

Change the datatype of the tensor by casting

In [ ]:
B = tf.constant([1.7, 3.5])
print (B)

B1 = tf.cast(B, dtype = tf.bfloat16)
B1

tf.Tensor([1.7 3.5], shape=(2,), dtype=float32)


<tf.Tensor: shape=(2,), dtype=bfloat16, numpy=array([1.70312, 3.5], dtype=bfloat16)>

Aggregating Tensors

In [ ]:
#Get the absolute value of the tensor
B = tf.constant([1, -2, -3, 4])
tf.abs(B)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
#Min value
print (tf.reduce_min(B))
#Max value
print (tf.reduce_max(B))
#Mean
print (tf.reduce_mean(B))
#Sum
print (tf.reduce_sum(B))

tf.Tensor(-3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


Finding the positional maximum and minimum

In [ ]:
#Create a tensor 
tf.random.set_seed(42)
tensor = tf.random.uniform(shape = [50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
tensor[tf.argmax(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

Squeezing the tensor

In [ ]:
tf.random.set_seed(42)
A = tf.random.uniform(shape = [1,1,1,1,50])
A

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
# Now squeeze the tensor to remove all the dimensions with 1 in them
A_new = tf.squeeze(A)
A_new.shape

TensorShape([50])

One hot encoding tensors

In [ ]:
B = [1,2,3,0,4]
B_new = tf.one_hot(B, depth=5)
B_new

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

Tensors and Numpy compatibility

In [ ]:
#Create a tensor through numpy
C = tf.constant(np.array([2.0, 4.0, 5.2]))
C

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2. , 4. , 5.2])>

In [ ]:
#reverse it back to an array
C_reverse = np.array(C)
C_reverse

array([2. , 4. , 5.2])

Accessing a GPU for computation

In [ ]:
#Check the hardware on which the program is running currently
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Thu Oct  7 18:49:13 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P0    72W / 149W |    123MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------